# Generated by Django 5.0.6 on 2024-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fistname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("phone", models.IntegerField(null=True)),
                ("joined_date", models.IntegerField(null=True)),
            ],
        ),
    ]
