# Generated by Django 5.0.6 on 2024-05-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="fistname",
            new_name="firstname",
        ),
    ]
