# Generated by Django 5.0.6 on 2024-05-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_rename_fistname_member_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(null=True),
        ),
    ]
